### ISSUE TITLE
Deletes on non-BQ Models fail?

### ISSUE THREAD

**Issue by vanetten** [michelson/BigBroda#17]
ActiveRecord::Error::NotImplementedFeature - This Adapter doesn't offer updating single rows, Google Big query is append only by design:
  bigbroda (0.0.5) lib/active_record/connection_adapters/bigquery_adapter.rb:174:in `delete_all'
  activerecord (4.1.6) lib/active_record/persistence.rb:466:in `destroy_row'

I have things configured with bquery defined within database.yml, GoogleBigquery configured within bigquery initializer, and  establish_bq_connection :bigquery executed within a single model.

Read operations on BQ backed model work fine, haven't tried rest of CRUD operation on BQ, since I'm working on a read-only BQ database.

CRUD operations on other sqlite3 backed models work fine, apart from delete? Somehow the delete_all method is being called on non-BQ Models. Any ideas?

Nice work BTW!! I forked your code with the aim of adding support for Google Genomics.

**Comment by vanetten** [comment]
This workaround worked!

# Example ActiveRecord interface to BigQuery
class Shakespeare < ActiveRecord::Base
  self.table_name = "shakespeare"
  self.primary_key = "word"
  # establish_bq_connection :bigquery
  self.establish_connection(
    :adapter => 'bigquery', 
    :project => "226864500698",
    :database => "test_as_big_query"
  )
end

**Comment by michelson** [comment]
Hi @vanetten , thanks for reporting this! you have found a very critical bug.
I've tested and I found that when you call .delete_all from non BQ model , and then call delete_all on a BQ one it will call the "DELETE * FROM" ! , and if you do this in reverse non BQ models will railse the NonImplementedFeature from Big Broda adapter !

I've fixed this on version 0.0.6. please confirm if it's working to close this 

best!
